/**
 * iConnect Email Placeholder Inventory
 *
 * Single source of truth that documents every placeholder token supported
 * across iConnect email channels (workflows, contracts, due diligence,
 * form submissions, meetings/bookings, event confirmations/reminders,
 * footer/socials).
 *
 * This module is documentation-only. Substitution logic still lives in:
 *   - api/_lib/emailService.js                  (replacePlaceholders, footer/socials)
 *   - api/_lib/workflows.js                     (workflow email actions, set_password_url)
 *   - server/workflowEngine.ts                  (TS workflow runner)
 *   - api/_lib/eventConfirmationEmail.js        (event confirmation emails)
 *   - api/cron/send-event-reminders.js          (event reminders)
 *   - api/cron/send-contract-reminders.js       (contract reminders)
 *   - api/cron/send-contract-timeout-notifications.js
 *   - api/due-diligence/_stageActions.js        (DD stage actions, contract requests)
 *   - api/due-diligence/test-fire-reminder.js
 *   - api/due-diligence/test-fire-timeout.js
 *   - api/dd-meeting-requests/{resend,add-alternative}.js
 *   - api/forms/send-submission-email.js        (form submission emails)
 *   - api/functions/[functionName].js           (member/team invites)
 *   - api/pending-purchase-orders/index.js      (PO reminder emails)
 *   - api/_lib/membershipFeeTokenEmail.js       (membership fee-link emails)
 *
 * Two syntaxes are supported by the engine:
 *   - {{token}}   — form-field / workflow-time substitutions
 *   - [[token]]   — core database lookups (member.*, organization.*, etc.)
 *
 * Many tokens are accepted in BOTH syntaxes — both forms are listed when that
 * is the case. New tokens should be added here and kept in sync with the
 * substitution code paths.
 */

export const PLACEHOLDER_SYNTAX = {
  CURLY: 'curly',
  BRACKET: 'bracket',
};

export const PLACEHOLDER_CATEGORIES = [
  'Member',
  'Organisation',
  'Contracts',
  'Due Diligence',
  'Meetings & Bookings',
  'Event Confirmation & Reminder',
  'Form Submissions',
  'Article Briefs',
  'Membership Fees',
  'Member Groups & Vacancies',
  'Workflow Triggers & Invites',
  'System & Links',
  'Footer & Socials',
];

export const PLACEHOLDER_CONTEXTS = [
  'Workflow Emails',
  'Contract Send / Reminders',
  'DD Stage Actions',
  'DD Reminders & Timeouts',
  'Meeting Booking Invitations',
  'Booking Confirmations',
  'Event Confirmations',
  'Event Reminders',
  'Form Submission Emails',
  'Member / Team Invites',
  'Purchase Order Reminders',
  'Article Brief Forms',
  'Membership Fee Link',
  'Vacancy Application Decisions',
  'Email Footer (all emails)',
];

const entry = (
  token,
  syntax,
  category,
  description,
  contexts,
  source,
  extras = {},
) => ({
  token,
  syntax,
  category,
  description,
  contexts,
  source,
  prerequisites: extras.prerequisites || null,
  notes: extras.notes || null,
});

export const EMAIL_PLACEHOLDERS = [
  // --- Member ---
  entry(
    '[[member.id]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Member',
    'Internal member record ID for the recipient (or trigger member).',
    ['Workflow Emails', 'Form Submission Emails', 'Member / Team Invites'],
    'api/_lib/emailService.js (replacePlaceholders), api/forms/send-submission-email.js',
  ),
  entry(
    '[[member.full_name]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Member',
    'Member full name (first + last).',
    ['Workflow Emails', 'Form Submission Emails', 'Member / Team Invites'],
    'api/_lib/emailService.js, api/forms/send-submission-email.js, api/functions/[functionName].js',
  ),
  entry(
    '[[member.first_name]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Member',
    'Member first name. Also resolved from booking.attendee_first_name in event emails.',
    ['Workflow Emails', 'Form Submission Emails', 'Event Confirmations', 'Event Reminders', 'Member / Team Invites'],
    'api/_lib/emailService.js, api/_lib/eventConfirmationEmail.js, api/cron/send-event-reminders.js',
  ),
  entry(
    '[[member.last_name]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Member',
    'Member last name.',
    ['Workflow Emails', 'Form Submission Emails', 'Event Confirmations', 'Event Reminders', 'Member / Team Invites'],
    'api/_lib/emailService.js, api/_lib/eventConfirmationEmail.js, api/cron/send-event-reminders.js',
  ),
  entry(
    '[[member.email]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Member',
    'Member email address.',
    ['Workflow Emails', 'Form Submission Emails', 'Event Confirmations', 'Event Reminders', 'Member / Team Invites'],
    'api/_lib/emailService.js, api/_lib/eventConfirmationEmail.js, api/cron/send-event-reminders.js',
  ),
  entry(
    '[[member.phone]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Member',
    'Member phone number.',
    ['Workflow Emails', 'Form Submission Emails'],
    'api/_lib/emailService.js (entityType=member direct lookup)',
  ),
  entry(
    '[[member_full_name]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Member',
    'Inviter full name in member/team invite emails (alias of [[member.full_name]]).',
    ['Member / Team Invites'],
    'api/functions/[functionName].js (member invite handler)',
  ),
  entry(
    '[[member_first_name]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Member',
    'Inviter first name in member/team invite emails.',
    ['Member / Team Invites'],
    'api/functions/[functionName].js',
  ),
  entry(
    '[[member_last_name]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Member',
    'Inviter last name in member/team invite emails.',
    ['Member / Team Invites'],
    'api/functions/[functionName].js',
  ),
  entry(
    '[[member_email]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Member',
    'Inviter email in member/team invite emails.',
    ['Member / Team Invites'],
    'api/functions/[functionName].js',
  ),
  entry(
    '{{first_name}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Member',
    'Recipient first name. Resolved from member or DD/contract recipient.',
    ['Workflow Emails', 'DD Stage Actions', 'DD Reminders & Timeouts'],
    'api/_lib/workflows.js, api/due-diligence/_stageActions.js',
  ),
  entry(
    '{{last_name}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Member',
    'Recipient last name.',
    ['Workflow Emails', 'DD Stage Actions'],
    'api/due-diligence/_stageActions.js',
  ),
  entry(
    '{{full_name}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Member',
    'Recipient full name.',
    ['DD Stage Actions'],
    'api/due-diligence/_stageActions.js',
  ),
  entry(
    '{{name}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Member',
    'Generic recipient name (member or organization, depending on context).',
    ['Workflow Emails', 'DD Stage Actions'],
    'api/_lib/workflows.js, api/due-diligence/_stageActions.js',
  ),
  entry(
    '{{email}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Member',
    'Recipient email address.',
    ['DD Stage Actions'],
    'api/due-diligence/_stageActions.js',
  ),
  entry(
    '{{member_first_name}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Member',
    'New member first name (DD-created member emails).',
    ['DD Stage Actions'],
    'api/due-diligence/_stageActions.js',
  ),
  entry(
    '{{member_last_name}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Member',
    'New member last name (DD-created member emails).',
    ['DD Stage Actions'],
    'api/due-diligence/_stageActions.js',
  ),
  entry(
    '{{member_email}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Member',
    'New member email (DD-created member emails).',
    ['DD Stage Actions'],
    'api/due-diligence/_stageActions.js',
  ),
  entry(
    '{{member.first_name}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Member',
    'Workflow placeholder resolved against the member entity.',
    ['Workflow Emails'],
    'api/_lib/workflows.js (replacePlaceholders entityType=member)',
  ),

  // --- Organisation ---
  entry(
    '[[organization.id]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Organisation',
    'Organisation record ID.',
    ['Workflow Emails', 'Form Submission Emails', 'Member / Team Invites'],
    'api/_lib/emailService.js, api/forms/send-submission-email.js',
  ),
  entry(
    '[[organization.name]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Organisation',
    'Organisation display name.',
    ['Workflow Emails', 'Contract Send / Reminders', 'DD Stage Actions', 'Form Submission Emails', 'Member / Team Invites'],
    'api/_lib/emailService.js, api/cron/send-contract-reminders.js, api/due-diligence/_stageActions.js',
  ),
  entry(
    '[[organization.invoicing_email]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Organisation',
    'Organisation invoicing/billing email address.',
    ['Workflow Emails', 'Form Submission Emails'],
    'api/_lib/emailService.js, api/forms/send-submission-email.js',
  ),
  entry(
    '[[organization.phone]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Organisation',
    'Organisation phone number.',
    ['Workflow Emails', 'Form Submission Emails'],
    'api/_lib/emailService.js, api/forms/send-submission-email.js',
  ),
  entry(
    '[[organization_id]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Organisation',
    'Organisation ID alias used by member-invite handler.',
    ['Member / Team Invites'],
    'api/functions/[functionName].js',
  ),
  entry(
    '[[organization_name]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Organisation',
    'Organisation name alias used by member-invite handler.',
    ['Member / Team Invites'],
    'api/functions/[functionName].js',
  ),
  entry(
    '{{organization.name}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Organisation',
    'Workflow placeholder resolved against the organisation entity.',
    ['Workflow Emails'],
    'api/_lib/workflows.js (replacePlaceholders entityType=organization)',
  ),
  entry(
    '{{organization_name}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Organisation',
    'Organisation name in DD-created member emails and member invites.',
    ['DD Stage Actions', 'Member / Team Invites'],
    'api/due-diligence/_stageActions.js, api/functions/[functionName].js',
  ),
  entry(
    '{{organization_id}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Organisation',
    'Organisation ID for member-invite emails.',
    ['Member / Team Invites'],
    'api/functions/[functionName].js',
  ),
  entry(
    '[[tenant.name]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Organisation',
    'Tenant (workspace / iConnect site) display name.',
    ['Contract Send / Reminders', 'DD Stage Actions'],
    'api/cron/send-contract-reminders.js, api/cron/send-contract-timeout-notifications.js, api/due-diligence/_stageActions.js',
  ),
  entry(
    '{{tenant_name}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Organisation',
    'Tenant display name (curly alias). Also resolves in booking confirmations.',
    ['DD Stage Actions', 'Booking Confirmations'],
    'api/due-diligence/_stageActions.js',
  ),

  // --- Contracts ---
  entry(
    '[[contract.name]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Contracts',
    'Name of the contract / form being signed.',
    ['Contract Send / Reminders'],
    'api/cron/send-contract-reminders.js, api/cron/send-contract-timeout-notifications.js, api/due-diligence/_stageActions.js',
  ),
  entry(
    '{{contract_name}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Contracts',
    'Contract name (curly alias).',
    ['Contract Send / Reminders'],
    'api/due-diligence/_stageActions.js',
  ),
  entry(
    '[[signer.name]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Contracts',
    'Full name of the contract signer.',
    ['Contract Send / Reminders'],
    'api/cron/send-contract-reminders.js, api/due-diligence/_stageActions.js',
  ),
  entry(
    '[[signer.first_name]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Contracts',
    'First name of the contract signer.',
    ['Contract Send / Reminders'],
    'api/cron/send-contract-reminders.js, api/due-diligence/_stageActions.js',
  ),
  entry(
    '[[signer.last_name]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Contracts',
    'Last name of the contract signer.',
    ['Contract Send / Reminders'],
    'api/cron/send-contract-reminders.js, api/due-diligence/_stageActions.js',
  ),
  entry(
    '[[signer.email]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Contracts',
    'Email of the contract signer.',
    ['Contract Send / Reminders'],
    'api/cron/send-contract-reminders.js, api/due-diligence/_stageActions.js',
  ),
  entry(
    '{{signer_name}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Contracts',
    'Full signer name (curly alias).',
    ['Contract Send / Reminders'],
    'api/due-diligence/_stageActions.js',
  ),
  entry(
    '{{signer_first_name}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Contracts',
    'Signer first name (curly alias).',
    ['Contract Send / Reminders'],
    'api/due-diligence/_stageActions.js',
  ),
  entry(
    '{{signer_last_name}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Contracts',
    'Signer last name (curly alias).',
    ['Contract Send / Reminders'],
    'api/due-diligence/_stageActions.js',
  ),
  entry(
    '{{signer_email}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Contracts',
    'Signer email (curly alias).',
    ['Contract Send / Reminders'],
    'api/due-diligence/_stageActions.js',
  ),
  entry(
    '{{sign_url}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Contracts',
    'Direct URL to the contract signing page for the recipient.',
    ['Contract Send / Reminders'],
    'api/due-diligence/_stageActions.js, api/cron/send-contract-reminders.js',
  ),
  entry(
    '{{signing_url}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Contracts',
    'Alias of {{sign_url}}.',
    ['Contract Send / Reminders'],
    'api/due-diligence/_stageActions.js',
  ),
  entry(
    '{{days_remaining}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Contracts',
    'Days remaining until the contract expiry deadline.',
    ['Contract Send / Reminders'],
    'api/cron/send-contract-reminders.js, api/cron/send-contract-timeout-notifications.js',
  ),
  entry(
    '{{days_since_sent}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Contracts',
    'Days since the contract invitation was sent.',
    ['Contract Send / Reminders'],
    'api/cron/send-contract-reminders.js',
  ),
  entry(
    '[[applicant.name]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Contracts',
    'Applicant full name in contract timeout notifications.',
    ['Contract Send / Reminders'],
    'api/cron/send-contract-timeout-notifications.js',
  ),

  // --- Due Diligence ---
  entry(
    '{{due_diligence_status}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Due Diligence',
    'Current DD workflow status (e.g. submitted, in_review, approved).',
    ['DD Stage Actions', 'DD Reminders & Timeouts'],
    'EmailTemplateManagement PLACEHOLDER_GROUPS / DD pipeline',
  ),
  entry(
    '{{due_diligence_stage}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Due Diligence',
    'Name of the current DD stage.',
    ['DD Stage Actions'],
    'EmailTemplateManagement PLACEHOLDER_GROUPS',
  ),
  entry(
    '{{due_diligence_score}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Due Diligence',
    'Computed DD score for the application.',
    ['DD Stage Actions'],
    'EmailTemplateManagement PLACEHOLDER_GROUPS',
  ),
  entry(
    '{{due_diligence_risk_level}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Due Diligence',
    'Calculated DD risk level (Low/Medium/High).',
    ['DD Stage Actions'],
    'EmailTemplateManagement PLACEHOLDER_GROUPS',
  ),
  entry(
    '{{due_diligence_form_name}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Due Diligence',
    'Name of the DD form/application.',
    ['DD Stage Actions'],
    'EmailTemplateManagement PLACEHOLDER_GROUPS',
  ),
  entry(
    '{{due_diligence_reviewer}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Due Diligence',
    'Name of the DD reviewer.',
    ['DD Stage Actions'],
    'EmailTemplateManagement PLACEHOLDER_GROUPS',
  ),
  entry(
    '{{due_diligence_review_date}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Due Diligence',
    'Date the DD review was completed.',
    ['DD Stage Actions'],
    'EmailTemplateManagement PLACEHOLDER_GROUPS',
  ),
  entry(
    '{{custom_message}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Due Diligence',
    'Free-text custom message entered when triggering a DD stage action (when prompt_custom_message is enabled).',
    ['DD Stage Actions'],
    'api/due-diligence/_stageActions.js',
  ),
  entry(
    '{{dd_owner}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Due Diligence',
    'Display name of the DD owner (or default fallback).',
    ['DD Stage Actions', 'Contract Send / Reminders'],
    'api/due-diligence/_stageActions.js',
  ),
  entry(
    '{{dd_owner_email}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Due Diligence',
    'Email address of the DD owner.',
    ['DD Stage Actions'],
    'api/due-diligence/_stageActions.js',
  ),
  entry(
    '[[dd_owner]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Due Diligence',
    'DD owner display name (bracket alias).',
    ['Contract Send / Reminders', 'DD Stage Actions'],
    'api/due-diligence/_stageActions.js',
  ),
  entry(
    '{{recipient_name}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Due Diligence',
    'Recipient full name for DD-triggered emails.',
    ['DD Stage Actions', 'Meeting Booking Invitations'],
    'api/due-diligence/_stageActions.js',
  ),
  entry(
    '{{recipient_first_name}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Due Diligence',
    'Recipient first name.',
    ['DD Stage Actions'],
    'api/due-diligence/_stageActions.js',
  ),
  entry(
    '{{recipient_last_name}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Due Diligence',
    'Recipient last name.',
    ['DD Stage Actions'],
    'api/due-diligence/_stageActions.js',
  ),
  entry(
    '{{recipient_email}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Due Diligence',
    'Recipient email address.',
    ['DD Stage Actions', 'Meeting Booking Invitations'],
    'api/due-diligence/_stageActions.js',
  ),
  entry(
    '[[recipient.name]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Due Diligence',
    'Recipient full name (bracket alias).',
    ['DD Stage Actions'],
    'api/due-diligence/_stageActions.js',
  ),
  entry(
    '[[recipient.first_name]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Due Diligence',
    'Recipient first name (bracket alias).',
    ['DD Stage Actions'],
    'api/due-diligence/_stageActions.js',
  ),
  entry(
    '[[recipient.last_name]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Due Diligence',
    'Recipient last name (bracket alias).',
    ['DD Stage Actions'],
    'api/due-diligence/_stageActions.js',
  ),
  entry(
    '[[recipient.email]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Due Diligence',
    'Recipient email (bracket alias).',
    ['DD Stage Actions'],
    'api/due-diligence/_stageActions.js',
  ),
  entry(
    '{{submission.id}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Due Diligence',
    'Internal ID of the DD application submission.',
    ['DD Stage Actions', 'Form Submission Emails'],
    'api/forms/send-submission-email.js',
  ),
  entry(
    '{{submission.application_uid}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Due Diligence',
    'Public application UID for the DD submission.',
    ['DD Stage Actions', 'Form Submission Emails'],
    'api/forms/send-submission-email.js',
  ),
  entry(
    '{{submission.workflow_status}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Due Diligence',
    'Workflow status string for the submission.',
    ['DD Stage Actions', 'Form Submission Emails'],
    'api/forms/send-submission-email.js',
  ),
  entry(
    '{{submission.due_diligence_score}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Due Diligence',
    'Computed DD score on the submission record.',
    ['DD Stage Actions', 'Form Submission Emails'],
    'api/forms/send-submission-email.js',
  ),
  entry(
    '{{submission.risk_level}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Due Diligence',
    'Computed risk level on the submission record.',
    ['DD Stage Actions', 'Form Submission Emails'],
    'api/forms/send-submission-email.js',
  ),

  // --- Meetings & Bookings ---
  entry(
    '{{recipient_name}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Meetings & Bookings',
    'Invitee name in meeting-booking invitation emails.',
    ['Meeting Booking Invitations'],
    'EmailTemplateManagement PLACEHOLDER_GROUPS / dd-meeting-requests',
    { notes: 'Same token reused from DD stage actions.' },
  ),
  entry(
    '{{recipient_email}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Meetings & Bookings',
    'Invitee email in meeting-booking invitation emails.',
    ['Meeting Booking Invitations'],
    'EmailTemplateManagement PLACEHOLDER_GROUPS',
  ),
  entry(
    '{{meeting_type}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Meetings & Bookings',
    'Name of the meeting type / template.',
    ['Meeting Booking Invitations', 'Booking Confirmations'],
    'api/dd-meeting-requests/{resend,add-alternative}.js, api/due-diligence/_stageActions.js',
  ),
  entry(
    '{{duration}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Meetings & Bookings',
    'Meeting duration (e.g. "30 minutes").',
    ['Meeting Booking Invitations', 'Booking Confirmations'],
    'EmailTemplateManagement PLACEHOLDER_GROUPS',
  ),
  entry(
    '{{agent_name}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Meetings & Bookings',
    'Host / booking agent display name.',
    ['Meeting Booking Invitations', 'Booking Confirmations'],
    'EmailTemplateManagement PLACEHOLDER_GROUPS',
  ),
  entry(
    '{{booking_url}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Meetings & Bookings',
    'Plain URL to the public booking page for this meeting type.',
    ['Meeting Booking Invitations'],
    'api/dd-meeting-requests/{resend,add-alternative}.js, api/due-diligence/_stageActions.js',
  ),
  entry(
    '{{booking_link}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Meetings & Bookings',
    'Pre-rendered HTML anchor ("Book a meeting") pointing at the booking URL.',
    ['Meeting Booking Invitations'],
    'api/dd-meeting-requests/{resend,add-alternative}.js, api/due-diligence/_stageActions.js',
  ),
  entry(
    '{{attendee_name}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Meetings & Bookings',
    'Confirmed attendee full name.',
    ['Booking Confirmations'],
    'EmailTemplateManagement PLACEHOLDER_GROUPS',
  ),
  entry(
    '{{attendee_email}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Meetings & Bookings',
    'Confirmed attendee email address.',
    ['Booking Confirmations'],
    'EmailTemplateManagement PLACEHOLDER_GROUPS',
  ),
  entry(
    '{{attendee_notes}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Meetings & Bookings',
    'Notes the attendee submitted with the booking.',
    ['Booking Confirmations'],
    'EmailTemplateManagement PLACEHOLDER_GROUPS',
  ),
  entry(
    '{{meeting_title}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Meetings & Bookings',
    'Title of the booked meeting.',
    ['Booking Confirmations'],
    'EmailTemplateManagement PLACEHOLDER_GROUPS',
  ),
  entry(
    '{{meeting_date}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Meetings & Bookings',
    'Localised meeting date (e.g. "Monday, 3 March 2026").',
    ['Booking Confirmations'],
    'EmailTemplateManagement PLACEHOLDER_GROUPS',
  ),
  entry(
    '{{meeting_time}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Meetings & Bookings',
    'Meeting start time.',
    ['Booking Confirmations'],
    'EmailTemplateManagement PLACEHOLDER_GROUPS',
  ),
  entry(
    '{{meeting_end_time}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Meetings & Bookings',
    'Meeting end time.',
    ['Booking Confirmations'],
    'EmailTemplateManagement PLACEHOLDER_GROUPS',
  ),
  entry(
    '{{meeting_timezone}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Meetings & Bookings',
    'Timezone the meeting times are expressed in.',
    ['Booking Confirmations'],
    'EmailTemplateManagement PLACEHOLDER_GROUPS',
  ),
  entry(
    '{{zoom_join_url}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Meetings & Bookings',
    'Zoom meeting join URL.',
    ['Booking Confirmations'],
    'EmailTemplateManagement PLACEHOLDER_GROUPS',
    { prerequisites: 'Meeting type integrated with Zoom.' },
  ),
  entry(
    '{{zoom_password}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Meetings & Bookings',
    'Zoom meeting password.',
    ['Booking Confirmations'],
    'EmailTemplateManagement PLACEHOLDER_GROUPS',
    { prerequisites: 'Zoom meeting created with password.' },
  ),
  entry(
    '{{teams_join_url}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Meetings & Bookings',
    'Microsoft Teams meeting join URL.',
    ['Booking Confirmations'],
    'EmailTemplateManagement PLACEHOLDER_GROUPS',
    { prerequisites: 'Meeting type integrated with Microsoft Teams.' },
  ),
  entry(
    '{{meeting_join_details}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Meetings & Bookings',
    'Smart "how to join" block resolved from the booking\'s meeting type. ' +
      'Renders the Zoom link + passcode, Teams link, or a friendly phone / ' +
      'in-person fallback message — so the template author does not need ' +
      'conditional logic. Use this instead of {{zoom_join_url}} / ' +
      '{{zoom_password}} / {{teams_join_url}} in DD booking confirmation emails.',
    ['Booking Confirmations'],
    'api/public/book/[slug].js (buildMeetingJoinDetails)',
  ),

  // --- Event Confirmation & Reminder ---
  entry(
    '[[attendee.first_name]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Event Confirmation & Reminder',
    'Attendee first name on the booking.',
    ['Event Confirmations', 'Event Reminders'],
    'api/_lib/eventConfirmationEmail.js, api/cron/send-event-reminders.js',
  ),
  entry(
    '[[attendee.last_name]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Event Confirmation & Reminder',
    'Attendee last name.',
    ['Event Confirmations', 'Event Reminders'],
    'api/_lib/eventConfirmationEmail.js, api/cron/send-event-reminders.js',
  ),
  entry(
    '[[attendee.email]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Event Confirmation & Reminder',
    'Attendee email address.',
    ['Event Confirmations', 'Event Reminders'],
    'api/_lib/eventConfirmationEmail.js, api/cron/send-event-reminders.js',
  ),
  entry(
    '[[event.name]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Event Confirmation & Reminder',
    'Event name (alias of [[event.title]]).',
    ['Event Confirmations', 'Event Reminders'],
    'api/_lib/eventConfirmationEmail.js, api/cron/send-event-reminders.js',
  ),
  entry(
    '[[event.title]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Event Confirmation & Reminder',
    'Event title.',
    ['Event Confirmations', 'Event Reminders'],
    'api/_lib/eventConfirmationEmail.js, api/cron/send-event-reminders.js',
  ),
  entry(
    '[[event.date]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Event Confirmation & Reminder',
    'Localised event start date.',
    ['Event Confirmations', 'Event Reminders'],
    'api/_lib/eventConfirmationEmail.js, api/cron/send-event-reminders.js',
  ),
  entry(
    '[[event.location]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Event Confirmation & Reminder',
    'Event location, or "Online Event" for online events.',
    ['Event Confirmations', 'Event Reminders'],
    'api/_lib/eventConfirmationEmail.js, api/cron/send-event-reminders.js',
  ),
  entry(
    '[[booking.id]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Event Confirmation & Reminder',
    'Internal booking record ID.',
    ['Event Confirmations'],
    'api/_lib/eventConfirmationEmail.js',
  ),
  entry(
    '[[booking.reference]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Event Confirmation & Reminder',
    'Human-friendly booking reference.',
    ['Event Confirmations'],
    'api/_lib/eventConfirmationEmail.js',
  ),
  entry(
    '[[booking.booking_reference]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Event Confirmation & Reminder',
    'Alias of [[booking.reference]].',
    ['Event Confirmations'],
    'api/_lib/eventConfirmationEmail.js',
  ),
  entry(
    '{{booking_id}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Event Confirmation & Reminder',
    'Booking ID (curly form).',
    ['Event Confirmations'],
    'api/_lib/eventConfirmationEmail.js',
  ),
  entry(
    '{{booking_reference}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Event Confirmation & Reminder',
    'Booking reference (curly form).',
    ['Event Confirmations'],
    'api/_lib/eventConfirmationEmail.js',
  ),
  entry(
    '[[booking.ticket_class]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Event Confirmation & Reminder',
    'Ticket class name (defaults to "Standard").',
    ['Event Confirmations'],
    'api/_lib/eventConfirmationEmail.js',
  ),
  entry(
    '[[booking.ticket_price]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Event Confirmation & Reminder',
    'Per-ticket price formatted in GBP, or "Free".',
    ['Event Confirmations'],
    'api/_lib/eventConfirmationEmail.js',
  ),
  entry(
    '[[booking.total_cost]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Event Confirmation & Reminder',
    'Total booking cost formatted in GBP, or "Free".',
    ['Event Confirmations'],
    'api/_lib/eventConfirmationEmail.js',
  ),
  entry(
    '[[booking.offer_discount_description]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Event Confirmation & Reminder',
    'Description of the discount/offer applied to the booking.',
    ['Event Confirmations'],
    'api/_lib/eventConfirmationEmail.js',
  ),
  entry(
    '[[booking.offer_discount_amount]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Event Confirmation & Reminder',
    'Saving amount from the applied discount/offer.',
    ['Event Confirmations'],
    'api/_lib/eventConfirmationEmail.js',
  ),
  entry(
    '[[booking.track_name]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Event Confirmation & Reminder',
    'Comma-separated list of track names the attendee is registered for.',
    ['Event Confirmations', 'Event Reminders'],
    'api/_lib/eventConfirmationEmail.js, api/cron/send-event-reminders.js',
  ),
  entry(
    '[[track_name]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Event Confirmation & Reminder',
    'Alias of [[booking.track_name]].',
    ['Event Confirmations', 'Event Reminders'],
    'api/_lib/eventConfirmationEmail.js, api/cron/send-event-reminders.js',
  ),
  entry(
    '[[zoom_link]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Event Confirmation & Reminder',
    'Zoom join link for the event (online events only).',
    ['Event Confirmations', 'Event Reminders'],
    'api/_lib/eventConfirmationEmail.js, api/cron/send-event-reminders.js',
    { prerequisites: 'Event configured as online with Zoom.' },
  ),
  entry(
    '[[session_schedule]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Event Confirmation & Reminder',
    'Pre-rendered HTML schedule of the attendee\u2019s sessions.',
    ['Event Confirmations', 'Event Reminders'],
    'api/_lib/eventConfirmationEmail.js, api/cron/send-event-reminders.js',
    { prerequisites: 'Event has tracks/sessions.' },
  ),
  entry(
    '[[session_zoom_links]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Event Confirmation & Reminder',
    'Pre-rendered HTML list of per-session Zoom links.',
    ['Event Confirmations', 'Event Reminders'],
    'api/_lib/eventConfirmationEmail.js, api/cron/send-event-reminders.js',
    { prerequisites: 'Sessions have individual Zoom links.' },
  ),

  // --- Form Submissions ---
  entry(
    '{{<field_id>}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Form Submissions',
    'Resolves to the value submitted for the form field whose ID (UUID) is between the braces.',
    ['Form Submission Emails', 'Workflow Emails'],
    'api/forms/send-submission-email.js, api/_lib/workflows.js (resolveFieldIdPlaceholder)',
    { notes: 'Replace <field_id> with the actual field UUID, e.g. {{4a53827a-d7f0-4e81-b0db-5671f537550a}}.' },
  ),
  entry(
    '{{<field_label>}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Form Submissions',
    'Resolves to the value of the field whose label matches the token (case-sensitive).',
    ['Form Submission Emails'],
    'api/forms/send-submission-email.js',
    { notes: 'Replace <field_label> with the form field\u2019s label.' },
  ),
  entry(
    '{{record.<field>}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Form Submissions',
    'Generic record-scoped lookup against the trigger entity (workflow context).',
    ['Workflow Emails'],
    'api/_lib/emailService.js (replacePlaceholders entityType=record)',
  ),
  entry(
    '[[record.<field>]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Form Submissions',
    'Generic record-scoped DB lookup against the trigger entity.',
    ['Workflow Emails'],
    'api/_lib/emailService.js (replacePlaceholders entityType=record)',
  ),

  // --- Workflow Triggers & Invites ---
  entry(
    '{{invite_link}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Workflow Triggers & Invites',
    'Member/team signup link for invite emails.',
    ['Member / Team Invites'],
    'api/functions/[functionName].js',
  ),
  entry(
    '{{inviter_name}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Workflow Triggers & Invites',
    'Display name of the inviting member.',
    ['Member / Team Invites'],
    'api/functions/[functionName].js',
  ),
  entry(
    '{{invitee_email}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Workflow Triggers & Invites',
    'Email of the invitee.',
    ['Member / Team Invites'],
    'api/functions/[functionName].js',
  ),
  entry(
    '[[job_posting.status]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'Workflow Triggers & Invites',
    'Status of the job posting entity (workflow context only).',
    ['Workflow Emails'],
    'api/_lib/workflows.js (job_posting field mappings)',
  ),
  entry(
    '{{current_date}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Workflow Triggers & Invites',
    'Date when the workflow runs. Used as a workflow action value (set_field source) and form field source.',
    ['Workflow Emails'],
    'api/_lib/workflows.js, api/forms/process-application.js',
    { notes: 'Used as a value source in workflows; not generally substituted into email body text.' },
  ),
  entry(
    '{{current_datetime}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Workflow Triggers & Invites',
    'Date and time when the workflow runs (workflow action value).',
    ['Workflow Emails'],
    'api/_lib/workflows.js',
  ),

  // --- System & Links ---
  entry(
    '{{set_password_url}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'System & Links',
    'Generates a one-time password-setup link for the recipient member and replaces the placeholder with an HTML "Set your password" anchor.',
    ['Workflow Emails', 'Form Submission Emails', 'DD Stage Actions'],
    'api/_lib/workflows.js (processSpecialPlaceholders), server/workflowEngine.ts, api/forms/send-submission-email.js',
    {
      prerequisites: 'Recipient must be a member record (not a free-text email). Whitespace and casing are tolerated, e.g. {{ set_password_url }}, {{SET_PASSWORD_URL}}.',
    },
  ),
  entry(
    '[[set_password_url]]',
    PLACEHOLDER_SYNTAX.BRACKET,
    'System & Links',
    'Bracket alias of {{set_password_url}} \u2014 same generation logic.',
    ['Workflow Emails', 'Form Submission Emails'],
    'api/_lib/workflows.js (processSpecialPlaceholders)',
  ),
  entry(
    '{{communication_preferences_link}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'System & Links',
    'Pre-rendered HTML link ("Manage communication preferences") to the recipient\u2019s preference centre.',
    ['Workflow Emails', 'DD Stage Actions'],
    'api/_lib/emailService.js (replacePlaceholders), api/due-diligence/_stageActions.js',
    { prerequisites: 'Tenant base URL, tenant ID and recipient member ID must be known.' },
  ),
  entry(
    '{{communication_preferences_url}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'System & Links',
    'Plain URL to the recipient\u2019s communication-preferences page.',
    ['Workflow Emails', 'DD Stage Actions'],
    'api/_lib/emailService.js, api/due-diligence/_stageActions.js',
    { prerequisites: 'Tenant base URL and recipient member ID required.' },
  ),
  entry(
    '{{timestamp}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'System & Links',
    'ISO timestamp emitted by the email engine for diagnostic / audit purposes.',
    ['Workflow Emails'],
    'api/_lib/emailService.js',
  ),

  // --- Footer & Socials ---
  entry(
    '{{linkedin_url}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Footer & Socials',
    'Tenant LinkedIn profile URL configured under Social Icons.',
    ['Email Footer (all emails)'],
    'api/_lib/emailService.js (replaceSocialPlaceholdersInFooter)',
    { prerequisites: 'Tenant must have LinkedIn URL set in social_icons_config.' },
  ),
  entry(
    '{{twitter_url}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Footer & Socials',
    'Tenant Twitter / X profile URL.',
    ['Email Footer (all emails)'],
    'api/_lib/emailService.js',
    { prerequisites: 'Tenant must have Twitter URL set in social_icons_config.' },
  ),
  entry(
    '{{facebook_url}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Footer & Socials',
    'Tenant Facebook page URL.',
    ['Email Footer (all emails)'],
    'api/_lib/emailService.js',
    { prerequisites: 'Tenant must have Facebook URL set in social_icons_config.' },
  ),
  entry(
    '{{instagram_url}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Footer & Socials',
    'Tenant Instagram profile URL.',
    ['Email Footer (all emails)'],
    'api/_lib/emailService.js',
    { prerequisites: 'Tenant must have Instagram URL set in social_icons_config.' },
  ),
  entry(
    '{{youtube_url}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Footer & Socials',
    'Tenant YouTube channel URL.',
    ['Email Footer (all emails)'],
    'api/_lib/emailService.js',
    { prerequisites: 'Tenant must have YouTube URL set in social_icons_config.' },
  ),

  // --- Article Briefs ---
  entry(
    '{{brief.title}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Article Briefs',
    'Title of the article brief whose copyright / case-study form is being sent.',
    ['Article Brief Forms'],
    'api/article-briefs/[briefId]/send-copyright-form.js, send-case-study-form.js',
  ),
  entry(
    '{{writer.first_name}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Article Briefs',
    'First name of the writer assigned to the brief (internal member or external writer).',
    ['Article Brief Forms'],
    'api/article-briefs/[briefId]/send-copyright-form.js',
  ),
  entry(
    '{{writer.last_name}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Article Briefs',
    'Last name of the writer assigned to the brief.',
    ['Article Brief Forms'],
    'api/article-briefs/[briefId]/send-copyright-form.js',
  ),
  entry(
    '{{writer.full_name}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Article Briefs',
    'Full name of the writer assigned to the brief.',
    ['Article Brief Forms'],
    'api/article-briefs/[briefId]/send-copyright-form.js',
  ),
  entry(
    '{{writer.email}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Article Briefs',
    'Email of the writer assigned to the brief.',
    ['Article Brief Forms'],
    'api/article-briefs/[briefId]/send-copyright-form.js',
  ),
  entry(
    '{{provider.first_name}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Article Briefs',
    'First name of the case-study provider (interviewee/external source).',
    ['Article Brief Forms'],
    'api/article-briefs/[briefId]/send-case-study-form.js',
  ),
  entry(
    '{{provider.last_name}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Article Briefs',
    'Last name of the case-study provider.',
    ['Article Brief Forms'],
    'api/article-briefs/[briefId]/send-case-study-form.js',
  ),
  entry(
    '{{provider.full_name}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Article Briefs',
    'Full name of the case-study provider.',
    ['Article Brief Forms'],
    'api/article-briefs/[briefId]/send-case-study-form.js',
  ),
  entry(
    '{{provider.email}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Article Briefs',
    'Email of the case-study provider.',
    ['Article Brief Forms'],
    'api/article-briefs/[briefId]/send-case-study-form.js',
  ),
  entry(
    '{{form_url}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Article Briefs',
    'Public URL to the copyright-assignment / permission form for the recipient. Pre-filled with the brief, recipient, and (for case studies) the upload URL.',
    ['Article Brief Forms'],
    'api/article-briefs/[briefId]/send-copyright-form.js, send-case-study-form.js',
  ),
  entry(
    '{{upload_url}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Article Briefs',
    'Public URL where the case-study provider uploads supporting assets. Only populated on the case-study form.',
    ['Article Brief Forms'],
    'api/article-briefs/[briefId]/send-case-study-form.js',
  ),

  // --- Membership Fees (fee-link email per tier; Task #995) ---
  entry(
    '{{payment_link}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Membership Fees',
    'HTML anchor pointing at the single-use payment / submit-PO page minted for the recipient. REQUIRED — the API refuses to save a tier whose chosen fee-link template is missing this token.',
    ['Membership Fee Link'],
    'api/_lib/membershipFeeTokenEmail.js',
    { prerequisites: 'Tier must have a fee_link_email_template_id picked on the Pricing step.' },
  ),
  entry(
    '{{recipient_name}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Membership Fees',
    'Display name addressed in the salutation. Falls back to the organisation name (or tenant name if missing).',
    ['Membership Fee Link'],
    'api/_lib/membershipFeeTokenEmail.js',
  ),
  entry(
    '{{organisation_name}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Membership Fees',
    'Name of the organisation being invoiced. {{organization_name}} is also accepted as a US-spelling alias.',
    ['Membership Fee Link'],
    'api/_lib/membershipFeeTokenEmail.js',
  ),
  entry(
    '{{organization_name}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Membership Fees',
    'US-spelling alias of {{organisation_name}}.',
    ['Membership Fee Link'],
    'api/_lib/membershipFeeTokenEmail.js',
  ),
  entry(
    '{{membership_year}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Membership Fees',
    'Membership year label the fee covers (e.g. "2026" or "2026/2027").',
    ['Membership Fee Link'],
    'api/_lib/membershipFeeTokenEmail.js',
  ),
  entry(
    '{{tier_label}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Membership Fees',
    'Tier band label resolved for the organisation (e.g. "Small School").',
    ['Membership Fee Link'],
    'api/_lib/membershipFeeTokenEmail.js',
  ),
  entry(
    '{{final_cost}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Membership Fees',
    'Net membership fee for the period, pre-formatted with the tenant currency symbol (e.g. "£249.00").',
    ['Membership Fee Link'],
    'api/_lib/membershipFeeTokenEmail.js',
  ),
  entry(
    '{{currency}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Membership Fees',
    'ISO currency code used for the fee (e.g. "GBP", "USD", "EUR").',
    ['Membership Fee Link'],
    'api/_lib/membershipFeeTokenEmail.js',
  ),
  entry(
    '{{vat_amount}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Membership Fees',
    'VAT/tax amount applied on top of the net fee, pre-formatted with the currency symbol. Empty string when no VAT applies.',
    ['Membership Fee Link'],
    'api/_lib/membershipFeeTokenEmail.js',
  ),
  entry(
    '{{total_with_vat}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Membership Fees',
    'Total payable including VAT, pre-formatted with the currency symbol. Empty string when no VAT applies (use {{final_cost}} instead).',
    ['Membership Fee Link'],
    'api/_lib/membershipFeeTokenEmail.js',
  ),
  entry(
    '{{po_number}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Membership Fees',
    'Existing Purchase Order number on file for this membership year. Empty string when no PO is on file yet.',
    ['Membership Fee Link'],
    'api/_lib/membershipFeeTokenEmail.js',
  ),
  entry(
    '{{expires_at}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Membership Fees',
    'Human-readable expiry date of the payment link (e.g. "4 May 2026").',
    ['Membership Fee Link'],
    'api/_lib/membershipFeeTokenEmail.js',
  ),
  entry(
    '{{xero_invoice_number}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Membership Fees',
    'Xero invoice number when an invoice has been pre-created for this fee (e.g. cron-scheduled renewals). Empty string for ad-hoc fee emails without a Xero invoice.',
    ['Membership Fee Link'],
    'api/_lib/membershipFeeTokenEmail.js',
  ),
  entry(
    '{{xero_online_invoice_url}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Membership Fees',
    'Xero "View online invoice" URL for the pre-created invoice. Empty string when the invoice has no online URL or none was created.',
    ['Membership Fee Link'],
    'api/_lib/membershipFeeTokenEmail.js',
  ),
  entry(
    '{{invoice_description}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Membership Fees',
    'The tier config\'s "Description for invoice" text (with {year} substituted), matching the fee line on the Xero/QBO invoice. Empty string when no description is configured.',
    ['Membership Fee Link'],
    'api/_lib/membershipFeeTokenEmail.js',
  ),
  entry(
    '{{tenant_name}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Membership Fees',
    'Name of the membership organisation issuing the fee (the tenant).',
    ['Membership Fee Link'],
    'api/_lib/membershipFeeTokenEmail.js',
  ),

  // --- Member Groups & Vacancies ---
  entry(
    '{{member_group_name}}',
    PLACEHOLDER_SYNTAX.CURLY,
    'Member Groups & Vacancies',
    'The name of the member group associated with a vacancy application. Resolves to the group\'s display name in approval and decline decision emails sent to applicants.',
    ['Vacancy Application Decisions'],
    'api/admin/email-placeholder-samples.js, api/_lib/emailService.js',
  ),
];

// Produce a short, human-readable label for a placeholder token, suitable for
// a chip/label in the email builder (e.g. '[[member.first_name]]' →
// 'Member · First name'). Falls back to a humanised token when the token is not
// in the inventory.
export function placeholderFriendlyLabel(token) {
  if (!token) return '';
  const found = EMAIL_PLACEHOLDERS.find((p) => p.token === token);
  const inner = String(token).replace(/^[\[{]+/, '').replace(/[\]}]+$/, '');
  const field = inner.split('.').pop().replace(/_/g, ' ').trim();
  const humanField = field ? field.charAt(0).toUpperCase() + field.slice(1) : token;
  if (found) return `${found.category} · ${humanField}`;
  return humanField;
}

export function groupPlaceholdersByCategory(placeholders = EMAIL_PLACEHOLDERS) {
  const grouped = new Map();
  for (const cat of PLACEHOLDER_CATEGORIES) grouped.set(cat, []);
  for (const p of placeholders) {
    if (!grouped.has(p.category)) grouped.set(p.category, []);
    grouped.get(p.category).push(p);
  }
  return Array.from(grouped.entries())
    .filter(([, items]) => items.length > 0)
    .map(([category, items]) => ({ category, items }));
}

export function filterPlaceholders(placeholders, { search = '', categories = [], contexts = [], syntax = null } = {}) {
  const q = search.trim().toLowerCase();
  return placeholders.filter((p) => {
    if (categories.length && !categories.includes(p.category)) return false;
    if (syntax && p.syntax !== syntax) return false;
    if (contexts.length && !contexts.some((c) => p.contexts.includes(c))) return false;
    if (q) {
      const hay = [
        p.token,
        p.description,
        p.category,
        p.source,
        p.notes || '',
        p.prerequisites || '',
        ...p.contexts,
      ]
        .join(' \u2022 ')
        .toLowerCase();
      if (!hay.includes(q)) return false;
    }
    return true;
  });
}
