export const CURATED_FONTS = [
  { value: 'Arial, sans-serif', label: 'Arial' },
  { value: "'Degular Medium', 'Poppins', sans-serif", label: 'Degular Medium' },
  { value: 'Georgia, serif', label: 'Georgia' },
  { value: 'Lato, sans-serif', label: 'Lato' },
  { value: "'Merriweather', serif", label: 'Merriweather' },
  { value: 'Montserrat, sans-serif', label: 'Montserrat' },
  { value: "'Open Sans', sans-serif", label: 'Open Sans' },
  { value: 'Oswald, sans-serif', label: 'Oswald' },
  { value: "'Playfair Display', serif", label: 'Playfair Display' },
  { value: 'Poppins, sans-serif', label: 'Poppins' },
  { value: 'Raleway, sans-serif', label: 'Raleway' },
  { value: 'Roboto, sans-serif', label: 'Roboto' },
  { value: "'Source Sans Pro', sans-serif", label: 'Source Sans Pro' },
  { value: "'Times New Roman', serif", label: 'Times New Roman' },
  { value: 'Urbanist, sans-serif', label: 'Urbanist' },
  { value: 'Verdana, sans-serif', label: 'Verdana' },
];

export const CURATED_GOOGLE_FONT_NAMES = [
  'Lato',
  'Merriweather',
  'Montserrat',
  'Open+Sans',
  'Oswald',
  'Playfair+Display',
  'Poppins',
  'Raleway',
  'Roboto',
  'Source+Sans+Pro',
  'Urbanist',
];

export const CURATED_GOOGLE_FONTS_URL =
  'https://fonts.googleapis.com/css2?' +
  CURATED_GOOGLE_FONT_NAMES.map(f => `family=${f}:wght@400;500;600;700`).join('&') +
  '&display=swap';

// A curated library of popular Google Fonts for the "browse" picker on the
// Installed Fonts page. Not the full Google Fonts catalogue (that needs an API
// key); admins can add anything else by typing the exact family name. Each
// entry's `category` drives the generic fallback in the stored CSS font-stack.
export const POPULAR_GOOGLE_FONTS = [
  { name: 'Roboto', category: 'sans-serif' },
  { name: 'Open Sans', category: 'sans-serif' },
  { name: 'Lato', category: 'sans-serif' },
  { name: 'Montserrat', category: 'sans-serif' },
  { name: 'Poppins', category: 'sans-serif' },
  { name: 'Inter', category: 'sans-serif' },
  { name: 'Raleway', category: 'sans-serif' },
  { name: 'Nunito', category: 'sans-serif' },
  { name: 'Nunito Sans', category: 'sans-serif' },
  { name: 'Work Sans', category: 'sans-serif' },
  { name: 'Rubik', category: 'sans-serif' },
  { name: 'Mulish', category: 'sans-serif' },
  { name: 'DM Sans', category: 'sans-serif' },
  { name: 'Manrope', category: 'sans-serif' },
  { name: 'Urbanist', category: 'sans-serif' },
  { name: 'Karla', category: 'sans-serif' },
  { name: 'Quicksand', category: 'sans-serif' },
  { name: 'Barlow', category: 'sans-serif' },
  { name: 'Josefin Sans', category: 'sans-serif' },
  { name: 'Oswald', category: 'sans-serif' },
  { name: 'PT Sans', category: 'sans-serif' },
  { name: 'Titillium Web', category: 'sans-serif' },
  { name: 'Fira Sans', category: 'sans-serif' },
  { name: 'Cabin', category: 'sans-serif' },
  { name: 'Hind', category: 'sans-serif' },
  { name: 'Heebo', category: 'sans-serif' },
  { name: 'Assistant', category: 'sans-serif' },
  { name: 'Signika', category: 'sans-serif' },
  { name: 'Archivo', category: 'sans-serif' },
  { name: 'Sora', category: 'sans-serif' },
  { name: 'Space Grotesk', category: 'sans-serif' },
  { name: 'Figtree', category: 'sans-serif' },
  { name: 'Plus Jakarta Sans', category: 'sans-serif' },
  { name: 'Outfit', category: 'sans-serif' },
  { name: 'Lexend', category: 'sans-serif' },
  { name: 'Merriweather', category: 'serif' },
  { name: 'Playfair Display', category: 'serif' },
  { name: 'Lora', category: 'serif' },
  { name: 'PT Serif', category: 'serif' },
  { name: 'Noto Serif', category: 'serif' },
  { name: 'Source Serif Pro', category: 'serif' },
  { name: 'Roboto Slab', category: 'serif' },
  { name: 'Bitter', category: 'serif' },
  { name: 'Crimson Text', category: 'serif' },
  { name: 'Libre Baskerville', category: 'serif' },
  { name: 'EB Garamond', category: 'serif' },
  { name: 'Cormorant Garamond', category: 'serif' },
  { name: 'Domine', category: 'serif' },
  { name: 'Spectral', category: 'serif' },
  { name: 'Zilla Slab', category: 'serif' },
  { name: 'Bebas Neue', category: 'display' },
  { name: 'Anton', category: 'display' },
  { name: 'Righteous', category: 'display' },
  { name: 'Comfortaa', category: 'display' },
  { name: 'Pacifico', category: 'handwriting' },
  { name: 'Dancing Script', category: 'handwriting' },
  { name: 'Caveat', category: 'handwriting' },
  { name: 'Lobster', category: 'display' },
  { name: 'JetBrains Mono', category: 'monospace' },
  { name: 'Fira Code', category: 'monospace' },
  { name: 'Source Code Pro', category: 'monospace' },
  { name: 'IBM Plex Mono', category: 'monospace' },
  { name: 'Space Mono', category: 'monospace' },
];
