const escape = value => String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
export function renderReview(manifest, review) {
  const table = (headers, rows) => `<div class="scroll"><table><thead><tr>${headers.map(h => `<th>${escape(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(row => `<tr>${row.map(cell => `<td>${escape(cell)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
  const departments = manifest.departments.map(department => {
    const rows = manifest.rows.filter(row => row.departmentId === department.id);
    return [department.id, rows.length, (rows.reduce((sum, row) => sum + Math.round(row.data.occupied_wte * 100), 0) / 100).toFixed(2)];
  });
  return `<!doctype html><html lang="en"><meta charset="utf-8"><title>BNMS direct workforce import review</title><style>body{margin:0;background:#f3f5f8;color:#172738;font:15px/1.6 system-ui,sans-serif}main{max-width:1100px;margin:30px auto;background:#fff;padding:40px}.notice{padding:18px;background:#fff3dd;border-left:5px solid #a66d00}.stats{display:flex;gap:12px;flex-wrap:wrap}.stat{background:#edf3f8;padding:16px;min-width:150px}.stat b{display:block;font-size:25px}table{border-collapse:collapse;width:100%;font-size:12px}th,td{border:1px solid #dce3eb;padding:8px;text-align:left}th{background:#edf3f8}.scroll{overflow:auto}code{overflow-wrap:anywhere}@media(max-width:700px){main{margin:0;padding:20px}}</style><main>
<p>BNMS · direct Workforce Row → Department · preparation review</p><h1>Prepared for review. Not authorized for installation or import.</h1>
<div class="notice"><strong>No destination database import or installation occurred.</strong> This package is offline-only. A separate, explicit final approval is required before destination SQL installation or invocation. Isolated synthetic local PostgreSQL validation is not a destination write or production trigger-parity claim.</div>
<div class="stats"><div class="stat"><b>1,242</b>source occurrences</div><div class="stat"><b>1,242</b>new direct edges</div><div class="stat"><b>1,708.14</b>occupied WTE</div><div class="stat"><b>8</b>existing Rows preserved</div></div>
<h2>Current direct contract</h2><p>Every imported <code>workforce_survey_row</code> receives one required direct edge through <code>a422da51-6005-4831-a69e-bf284ff6f124</code> to its existing <code>org_department</code>. No surveys, survey edges, annual records, or row names are inserted. <code>Reporting_Year</code> was validated as a source invariant only and is not imported. The active primary display field is pinned to <code>staff_group</code>.</p>
<h2>Source fidelity</h2><p>The exact source SHA-256 is <code>${escape(manifest.sourceSha256)}</code>. All 1,242 physical source occurrences are retained, including 132 beyond-first occurrences in 84 normalized duplicate groups (216 rows). Each provenance identity is SHA-256 of tenant, Row object, exact source bytes hash, and physical source line.</p>
${table(['Source treatment', 'Direct Row payload'], [['Staff_Group', 'staff_group; exact canonical dropdown string retained'], ['Grade', 'grade; exact canonical dropdown string retained'], ['Occupied_Nuclear_Medicine_WTE', 'occupied_wte'], ['Legacy_Vacancy_Reported', 'legacy_vacancy_reported; 53 source blanks become No'], ['Reporting_Year / row_name', 'omitted'], ['vacant_wte', 'omitted (not null or zero)']])}
<p>The live snapshot is pinned before import. Canonical dropdown values are exact, including trailing spaces. Metadata is read and compared only; it is never mutated. Normal database triggers remain enabled.</p>
<h2>Atomic, service-only future operation</h2><p>The reviewed SQL creates direct-import provenance ledgers and a service-role-only, parameterless function. It requires the exact approval interlock, locks metadata/record/relationship tables in one transaction, refuses baseline or source overlap, and either commits all 1,242 records, 1,242 edges, and ledger entries or rolls back. Replay creates nothing: it proves every payload, source occurrence, Department edge, and the existing eight-row baseline exactly; it never repairs drift.</p>
<h2>Audit and review limits</h2><p>Destination <code>lvmzliemqnieeoruhkik</code> was represented by two complete matching GET-only reads at <code>${escape(review.observation.observedAt || review.observation.finishedAt || 'recorded observation')}</code>. The package generator refuses incomplete evidence, changed state, an active <code>row_name</code>, a non-<code>staff_group</code> primary display, relationship drift, or anything other than the eight-row baseline.</p>
<p>Offline tests and source inspection do not prove live SQL parsing, permissions, trigger behavior, lock timing, or rollback. Before any separately approved execution, repeat the GET audit, compare all package hashes, verify destination and TLS, use a quiet window, and perform read-only post-commit/replay verification.</p>
${table(['Artifact', 'SHA-256'], [['Original CSV', manifest.sourceSha256], ['Manifest', review.manifestSha256], ['Install SQL', review.installSqlSha256], ['Invoke SQL', review.invokeSqlSha256]])}
<h2>Per-Department direct-row plan</h2>${table(['Existing Department UUID', 'Rows', 'Occupied WTE'], departments)}</main>`;
}