import { useEffect, useMemo, useRef, useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Search, Loader2 } from 'lucide-react';

// Task #1867: searchable Font Awesome icon picker for the Text block bullet
// icon. The icon dataset (client/src/lib/faIcons.json) is generated by
// scripts/generate-fa-icons.mjs from the @fortawesome/fontawesome-free
// metadata. It's dynamically imported so the ~280KB list never weighs down
// the initial canvas bundle — it only loads when an author opens the picker.

const STYLE_PREFIX = { solid: 'fa-solid', regular: 'fa-regular', brands: 'fa-brands' };
const STYLE_FILTERS = [
  { value: 'all', label: 'All' },
  { value: 'solid', label: 'Solid' },
  { value: 'regular', label: 'Regular' },
  { value: 'brands', label: 'Brands' },
];
const MAX_RESULTS = 300;

// Build the Font Awesome class string for an icon in a given style, e.g.
// "fa-solid fa-book-open". Falls back to whatever style the icon actually has.
function classFor(icon, style) {
  const useStyle = icon.s.includes(style) ? style : icon.s[0];
  return `${STYLE_PREFIX[useStyle] || 'fa-solid'} fa-${icon.n}`;
}

export function FontAwesomeIconPicker({ open, onClose, onSelect, currentValue }) {
  const [icons, setIcons] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(false);
  const [query, setQuery] = useState('');
  const [styleFilter, setStyleFilter] = useState('all');
  const searchRef = useRef(null);

  // Lazily load the dataset the first time the dialog opens.
  useEffect(() => {
    if (!open || icons || loading) return;
    let cancelled = false;
    setLoading(true);
    setError(false);
    import('@/lib/faIcons.json')
      .then((mod) => {
        if (cancelled) return;
        setIcons(mod.default || mod);
        setLoading(false);
      })
      .catch(() => {
        if (cancelled) return;
        setError(true);
        setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [open, icons, loading]);

  useEffect(() => {
    if (open) {
      // Defer focus so the dialog content has mounted.
      const t = setTimeout(() => searchRef.current?.focus(), 50);
      return () => clearTimeout(t);
    }
  }, [open]);

  const results = useMemo(() => {
    if (!icons) return [];
    const q = query.trim().toLowerCase();
    const out = [];
    for (const icon of icons) {
      if (styleFilter !== 'all' && !icon.s.includes(styleFilter)) continue;
      if (q) {
        const hay = `${icon.n} ${icon.l} ${(icon.t || []).join(' ')}`.toLowerCase();
        if (!hay.includes(q)) continue;
      }
      out.push(icon);
      if (out.length >= MAX_RESULTS) break;
    }
    return out;
  }, [icons, query, styleFilter]);

  // The effective style used when rendering / selecting a grid icon: when a
  // specific style filter is active, honour it; otherwise use the icon's own
  // best style.
  const styleForGrid = styleFilter === 'all' ? null : styleFilter;

  const handlePick = (icon) => {
    onSelect(classFor(icon, styleForGrid || 'solid'));
    onClose();
  };

  return (
    <Dialog open={open} onOpenChange={(o) => { if (!o) onClose(); }}>
      <DialogContent className="max-w-2xl" data-testid="dialog-icon-picker">
        <DialogHeader>
          <DialogTitle>Choose a bullet icon</DialogTitle>
        </DialogHeader>
        <div className="space-y-3">
          <div className="relative">
            <Search className="absolute left-2 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400 pointer-events-none" />
            <Input
              ref={searchRef}
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder="Search icons (e.g. book, arrow, star)…"
              className="h-9 pl-8"
              data-testid="input-icon-search"
            />
          </div>
          <div className="flex flex-wrap gap-1">
            {STYLE_FILTERS.map((f) => (
              <Button
                key={f.value}
                type="button"
                size="sm"
                variant={styleFilter === f.value ? 'default' : 'outline'}
                onClick={() => setStyleFilter(f.value)}
                data-testid={`button-icon-style-${f.value}`}
              >
                {f.label}
              </Button>
            ))}
          </div>

          {loading && (
            <div className="flex items-center justify-center gap-2 py-12 text-sm text-slate-500" data-testid="status-icon-loading">
              <Loader2 className="w-4 h-4 animate-spin" /> Loading icons…
            </div>
          )}
          {error && (
            <div className="py-12 text-center text-sm text-slate-500" data-testid="status-icon-error">
              Could not load icons. You can still type a class name manually.
            </div>
          )}

          {!loading && !error && icons && (
            <>
              <div
                className="grid grid-cols-6 sm:grid-cols-8 gap-1 max-h-[50vh] overflow-y-auto pr-1"
                data-testid="grid-icons"
              >
                {results.map((icon) => {
                  const cls = classFor(icon, styleForGrid || 'solid');
                  const isCurrent = currentValue && String(currentValue).trim() === cls;
                  return (
                    <button
                      key={`${icon.n}-${styleForGrid || icon.s[0]}`}
                      type="button"
                      onClick={() => handlePick(icon)}
                      title={icon.l}
                      className={`flex flex-col items-center justify-center gap-1 rounded-md p-2 hover-elevate active-elevate-2 ${isCurrent ? 'ring-2 ring-primary' : ''}`}
                      data-testid={`icon-option-${icon.n}`}
                    >
                      <i className={`${cls} text-lg text-slate-700`} aria-hidden="true" />
                      <span className="w-full truncate text-center text-[9px] text-slate-500">{icon.l}</span>
                    </button>
                  );
                })}
              </div>
              <div className="flex items-center justify-between gap-2 text-xs text-slate-500">
                <span data-testid="text-icon-result-count">
                  {results.length === 0
                    ? 'No icons match your search'
                    : `Showing ${results.length}${results.length >= MAX_RESULTS ? '+' : ''} icon${results.length === 1 ? '' : 's'}`}
                </span>
              </div>
            </>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}

export default FontAwesomeIconPicker;
