// Built-in URL aliases for the members list page. Each alias gets a real
// route registered in client/src/pages/index.jsx (list + detail). Custom
// terms outside this list are handled by DynamicMemberRedirector.
export const BUILTIN_MEMBER_ALIASES = ['members', 'contacts', 'individuals', 'people'];

// Top-level route roots (lowercased) that a custom members slug must never
// shadow. Derived from the routes registered in client/src/pages/index.jsx.
// A custom plural term whose slug collides with one of these is rejected at
// save time and ignored by DynamicMemberRedirector.
export const RESERVED_MEMBER_SLUGS = new Set([
  '',
  'about-me',
  'aboutme',
  'accessibilityaudits',
  'admin',
  'adminmemberedit',
  'adminsetup',
  'aireports',
  'articleeditor',
  'articles',
  'articlessettings',
  'articleview',
  'auth',
  'awardmanagement',
  'balances',
  'booking-agents',
  'bookings',
  'borderradiussettings',
  'briefdetail',
  'briefmanagement',
  'briefsettings',
  'buttonelements',
  'buttonstylemanagement',
  'buyprogramtickets',
  'campaigns',
  'cancellationrequests',
  'canvaslinksmanager',
  'canvaspageeditor',
  'carddeckmanagement',
  'casestudyupload',
  'categorymanagement',
  'communicationsmanagement',
  'complexeventdetail',
  'cpdcertificatetemplates',
  'content',
  'createcomplexevent',
  'createevent',
  'customfieldsadmin',
  'customobjectsadmin',
  'dashboard',
  'dataexport',
  'discountcodemanagement',
  'domain-settings',
  'domainsettings',
  'duediligenceconfig',
  'duediligencedashboard',
  'duediligencereports',
  'dynamicdirectorymanagement',
  'dynamicpage',
  'editevent',
  'emailplaceholders',
  'email-preferences',
  'emailtemplatemanagement',
  'embed',
  'eventcheckin',
  'eventcheckindashboard',
  'eventdetails',
  'eventregistrationreport',
  'events',
  'eventsettings',
  'external-writers',
  'externalwriters',
  'filemanagement',
  'floatermanagement',
  'formbuilder',
  'formconversionreport',
  'formmanagement',
  'formsettings',
  'formsubmissions',
  'formview',
  'forum',
  'forummanagement',
  'forumthread',
  'fundraiser',
  'fundraisingmanagement',
  'groupemail',
  'groupevents',
  'groupprojects',
  'guestwritermanagement',
  'help',
  'history',
  'home',
  'icontent',
  'ieditpageeditor',
  'ieditpagemanagement',
  'iedittemplatemanagement',
  'importmanager',
  'inbox',
  'installedfonts',
  'jobboard',
  'jobboardsettings',
  'jobdetails',
  'jobpostingmanagement',
  'jobpostsuccess',
  'login',
  'memberdemo',
  'memberdirectory',
  'memberdirectorysettings',
  'membergroupassignmentreport',
  'membergroupdetail',
  'membergroupguestmanagement',
  'membergroupinvitereport',
  'membergroupmanagement',
  'membergroups',
  'membergroupsettings',
  'memberhandlemanagement',
  'memberpreferences',
  'memberroleassignment',
  'memberrolereport',
  'membershipfees',
  'membershipsettings',
  'membershiptiermanagement',
  'micrositemanagement',
  'mybookings',
  'myjobpostings',
  'myorganisation',
  'mytickets',
  'navigationmanagement',
  'news',
  'newseditor',
  'newssettings',
  'newsview',
  'organisationdirectory',
  'organisationdirectorysettings',
  'organisationengagementreport',
  'organisationpreferences',
  'organisations',
  'pagebannermanagement',
  'pagevisibilitysettings',
  'paramtest',
  'pendingpurchaseordersreport',
  'photogalleries',
  'platform',
  'portalmenumanagement',
  'portalnavigationmanagement',
  'postjob',
  'preferences',
  'preferencesettings',
  'projectboards',
  'publicabout',
  'publicarticles',
  'publiccomplexevents',
  'publiccontact',
  'publicevents',
  'publicnews',
  'publicresources',
  'redirectmanagement',
  'register',
  'reportsdashboard',
  'reset-password',
  'resetpassword',
  'resourcemanagement',
  'resources',
  'resourcesettings',
  'reviewsubmission',
  'roleaccessconfigmanagement',
  'rolemanagement',
  'search',
  'sharon',
  'signup',
  'signup-verify',
  'sitemap',
  'speakermanagement',
  'sponsormanagement',
  'support',
  'supportmanagement',
  'tagmanagement',
  'team',
  'teamengagementreport',
  'teaminvitesettings',
  'teammembermanagement',
  'teamsettings',
  'testpage',
  'ticketsalesanalytics',
  'tourmanagement',
  'trainingfundmanagement',
  'unpackedinternationalemployability',
  'viewpage',
  'volunteerboard',
  'vouchermanagement',
  'walloffamemanagement',
  'workflowmanagement',
  'zoomwebinarprovisioning',
  // Task #3638: remaining static route roots registered in
  // client/src/pages/index.jsx (React Router matches case-insensitively, so
  // any explicit <Route path="/X"> shadows a page saved at /x). A regression
  // test (client/src/lib/reservedPageSlug.test.mjs) parses the route table
  // and fails if a new static route root is missing from this set.
  'article-preview',
  'badgemanagement',
  'bnmsmemberdemo',
  'book',
  'campaignedit',
  'dd-migrate',
  'dd-setup',
  'directdebitadmin',
  'directory',
  'donate',
  'emailcampaignedit',
  'eventbudgetreport',
  'formsubmission',
  'fundraise',
  'gallery',
  'group-booking',
  'group-role-invite',
  'guest-approval',
  'membergroupclassificationreport',
  'membership',
  'membership-fees',
  'monthlyfinancereport',
  'news-preview',
  'organisationgroups',
  'projectboard',
  'session-events',
  'submit-po',
  'survey',
  'surveyreports',
  'team-invite',
]);

export function isReservedMemberSlug(slug) {
  if (!slug) return false;
  const lower = String(slug).toLowerCase();
  if (BUILTIN_MEMBER_ALIASES.includes(lower)) return false;
  return RESERVED_MEMBER_SLUGS.has(lower);
}

// Task #3638: page-slug reservation for Canvas Builder / iEdit pages.
// Unlike isReservedMemberSlug, the built-in member aliases ARE reserved here:
// /people, /members, /contacts, /individuals have explicit routes to the CRM
// members list that win over the /:slug DynamicPage catch-all, so a page
// saved with one of those slugs is silently unreachable (gfi.dev.iconn.app
// /people incident). Microsite-assigned pages serve at /{prefix}/{slug} and
// never collide with top-level routes — callers must skip this check for them.
export function isReservedPageSlug(slug) {
  if (!slug) return false;
  const lower = String(slug).toLowerCase();
  // 'login' is the ONE reserved root a page may legitimately own: the
  // system login canvas page is created at slug 'login' (Create Login Page
  // flow) and the /login route renders it. Its own protections (immutable
  // slug, login-form publish gate) live in the entity update path, and the
  // duplicate-slug check prevents a second one.
  if (lower === 'login') return false;
  return RESERVED_MEMBER_SLUGS.has(lower) || BUILTIN_MEMBER_ALIASES.includes(lower);
}

// Consistent author-facing message for every surface that rejects a slug.
export function reservedPageSlugMessage(slug) {
  return `"/${String(slug || '').toLowerCase()}" is a built-in app route — choose a different slug`;
}
