import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import pg from 'pg';
import { runMigration, migrationUrl } from '../../scripts/apply-member-group-custom-fields.mjs';

test('migration replay, singleton/CAS, service grants, tenant values and deletion races', async t => {
  const root = await mkdtemp(join(tmpdir(), 'group-fields-'));
  const port = 46000 + Math.floor(Math.random() * 10000);
  execFileSync('initdb', ['-D', join(root, 'data'), '-A', 'trust', '-U', 'postgres'], { stdio: 'ignore' });
  execFileSync('pg_ctl', ['-D', join(root, 'data'), '-o', `-F -p ${port} -k ${root}`, '-w', 'start'], { stdio: 'ignore' });
  const c = new pg.Client({ host: root, port, user: 'postgres', database: 'postgres' });
  await c.connect();
  const concurrent = new pg.Client({ host: root, port, user: 'postgres', database: 'postgres' });
  await concurrent.connect();
  t.after(async () => {
    await concurrent.end();
    await c.end();
    execFileSync('pg_ctl', ['-D', join(root, 'data'), '-m', 'immediate', 'stop'], { stdio: 'ignore' });
    await rm(root, { recursive: true, force: true });
  });
  await c.query(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role;
    CREATE TABLE system_settings(id uuid PRIMARY KEY, tenant_id uuid, setting_key text, setting_value text);
    CREATE TABLE member_group(id uuid PRIMARY KEY, tenant_id uuid, name text);
    ALTER TABLE system_settings ENABLE ROW LEVEL SECURITY;
    CREATE POLICY original ON system_settings FOR ALL USING(true) WITH CHECK(true);
    GRANT SELECT,INSERT,UPDATE,DELETE ON system_settings TO authenticated;`);
  const sql = await readFile(migrationUrl, 'utf8');
  await runMigration(c, sql);
  await runMigration(c, sql);
  const tenant = '00000000-0000-0000-0000-000000000010';
  const other = '00000000-0000-0000-0000-000000000020';
  const id = '00000000-0000-0000-0000-000000000001';
  const field = { id, name: 'Count', type: 'number', show_on_detail: false, choices: [] };
  const save = (fields, revision) => c.query('SELECT save_member_group_custom_fields($1,$2,$3)', [tenant, JSON.stringify(fields), revision]);
  await c.query('SET ROLE service_role');
  await save([field], 0);
  await assert.rejects(save([field], 0), { code: '40001' });
  await c.query('RESET ROLE');
  await c.query('INSERT INTO member_group VALUES($1,$2,$3,$4)', [id, tenant, 'Group', JSON.stringify({ [id]: 0 })]);
  await assert.rejects(c.query('INSERT INTO member_group VALUES($1,$2,$3,$4)', [other, other, 'Other', JSON.stringify({ [id]: 0 })]), /Unknown/);
  await assert.rejects(save([{ ...field, type: 'text' }], 1), /reinterpreted/);
  await save([{ ...field, name: 'Renamed', show_on_detail: true }], 1);
  assert.equal((await c.query('SELECT custom_field_values FROM member_group')).rows[0].custom_field_values[id], 0);
  await c.query('SET ROLE authenticated');
  assert.equal((await c.query('SELECT * FROM system_settings')).rowCount, 0);
  await assert.rejects(save([], 2), { code: '42501' });
  await c.query('RESET ROLE');
  await c.query('BEGIN');
  await save([], 2);
  let finished = false;
  const racingWrite = concurrent.query('UPDATE member_group SET custom_field_values=$1', [JSON.stringify({ [id]: 1 })])
    .then(() => { finished = true; return null; }, error => { finished = true; return error; });
  await new Promise(resolve => setTimeout(resolve, 100));
  assert.equal(finished, false, 'value writes wait for the definition transaction');
  await c.query('COMMIT');
  assert.match((await racingWrite).message, /Unknown/);
  assert.deepEqual((await c.query('SELECT custom_field_values FROM member_group')).rows[0].custom_field_values, {}, 'definition deletion atomically erases stored values');
  await c.query("UPDATE member_group SET name='Still valid'");
  await assert.rejects(c.query('UPDATE member_group SET custom_field_values=$1', [JSON.stringify({ [id]: 1 })]), /Unknown/);
  await c.query("UPDATE member_group SET custom_field_values='{}'");
  assert.deepEqual((await c.query('SELECT custom_field_values FROM member_group')).rows[0].custom_field_values, {});
  assert.equal((await c.query('SELECT * FROM system_settings')).rowCount, 1);
});
